micronaut:
  application:
    name: testApi
  server:
    cors:
      enabled: true
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: jdbc:mariadb://localhost:3308/pokemon
    username: root
    password: my-secret-pw
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml
