name: Java CI with Gradle

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Give gradle executable permissions
        run: chmod +x ./gradlew
      - name: Run gradle build
        run: ./gradlew build
      - run: ls
      - name: upload jar
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*-all.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
      - name: List Directory
        run: ls
      - name: Deploy to Elastic Bean
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          application_name: ${{ env.BEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ env.APPLICATION_ENVIRONMENT }}
#          version_label: ${{ github.sha }}
          version_label: $(git rev-parse --short "$GITHUB_SHA")
          region: ap-south-1
          deployment_package: test-api-0.1-all.jar